"""oauth

Revision ID: 6324574ac773
Revises: 61c034e875dd
Create Date: 2019-11-22 09:42:45.626371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6324574ac773'
down_revision = '61c034e875dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'o_auth2_token',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=40), nullable=True),
        sa.Column('token_type', sa.String(length=40), nullable=True),
        sa.Column('access_token', sa.String(length=200), nullable=True),
        sa.Column('refresh_token', sa.String(length=200), nullable=True),
        sa.Column('expires_at', sa.Integer(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id']),
        sa.PrimaryKeyConstraint('id'),
    )
    op.add_column('user', sa.Column('link', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('type', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'type')
    op.drop_column('user', 'link')
    op.drop_table('o_auth2_token')
    # ### end Alembic commands ###
