"""empty message

Revision ID: 6bcebbb3e042
Revises: 9b30a907767b
Create Date: 2018-09-10 14:38:54.900373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bcebbb3e042'
down_revision = '9b30a907767b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('settings', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'settings')
    # ### end Alembic commands ###
