"""empty message

Revision ID: 9b30a907767b
Revises: 
Create Date: 2017-11-05 12:15:01.419014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b30a907767b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', sa.String(length=100), nullable=True))
    op.drop_column('post', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('url', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###
